import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "./components/NavigationBar";
import Link from "next/link";
import ViewCanvas from "./components/ViewCanvas";

//const geistSans = Geist({
//  variable: "--font-geist-sans",
//  subsets: ["latin"],
//});

//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.className} antialiased`}
      >
        <div className="fixed top-0 left-0 w-full flex justify-between items-center px-8 py-4">
          <Link className="text-lg" href="/">VIVIAN ZHOU</Link>
          <NavigationBar />
        </div>
        
        {children}
        <ViewCanvas />
      </body>
    </html>
  );
}
